### ISSUE TITLE
请教一个问题，fork pr 如何再同步

### ISSUE THREAD

**Issue by lymslive** [voldikss/vim-wenyan#3]
我之前很少在 github 上与友人协作。上次尝试提个 pr.
但我另有一个问题，当我 fork 之后，假如有别人 pr merger 了，或你自己改动过主 repos,
那之前 fork 的 repos 如何再同步最新的呢

**Comment by voldikss** [comment]
我一般是更改 remote url 然后 git pull 最后再改回去，比较麻烦，
https://www.zhihu.com/answer/44606041
这里的办法更好

lymslive <notifications@github.com> 于 2020年1月2日周四 下午6:10写道：

**Comment by lymslive** [comment]
谢谢, got it
